name: Test Github Actions
on: workflow_call

jobs:
  tsc_compliance_test:
    name: TSC Compliance Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0 https://github.com/actions/checkout/commit/24cb9080177205b6e8c946b17badbe402adc938f
        with:
          path: amplify-js
      - name: Setup node and build the repository
        uses: ./amplify-js/.github/actions/node-and-build
      - name: Run GithubAction tests
        working-directory: ./amplify-js
        run: yarn test:tsc-compliance
